const ActionTypes = {
  isLogin: 'IS_LOGIN',
  showAlert: 'SHOW_ALERT',
  hideAlert: 'HIDE_ALERT',
  showLoading: 'SHOW_LOADING',
  hideLoading: 'HIDE_LOADING',

  //user 
  USER_DATA: 'USER_DATA',
  LOGOUT: 'LOGOUT',

  //App
  EXTRA_CONTENT: 'EXTRA_CONTENT',
  GET_MOREDATA: 'GET_MOREDATA',
  GET_ALL_CARDS: 'GET_ALL_CARDS',
  DEL_CARD: 'DEL_CARD',

  //booking request
  GET_ACTIVE_BOOKING_REQUESTS:'GET_ACTIVE_BOOKING_REQUESTS',
  GET_PAST_BOOKING_REQUESTS:'GET_PAST_BOOKING_REQUESTS',
  GET_UPCOMMING_BOOKING_REQUESTS:'GET_UPCOMMING_BOOKING_REQUESTS',
  GET_BOOKING_REQUESTS_DETAILS:'GET_BOOKING_REQUESTS_DETAILS',

  //reviews
  GET_REVIEWS:'GET_REVIEWS',

  //Cart
  ADD_TO_CART: 'ADD_TO_CART'

};

export default ActionTypes;
